### PR TITLE
jus' a lil' grammar!

### PR DESCRIPTION
**Pull request by jeffjennings**
Looking out 4 u!

### CODE REVIEW

**Comment by adrn** [comment]
Big boy cat disagreez
image

**Comment by jeffjennings** [comment]
oh God...you didn't mention me by name did u?

**Comment by adrn** [comment]
You dug that grave yourself, unfortunately. Better start purging before the Wayback Machine finds this page!

**Comment by jeffjennings** [comment]
plz tell my family I loved them.

**Pull request closed without merging**
